### ISSUE TITLE
Consider using one paypal order per each solidus order

### ISSUE THREAD

**Issue by elia** [nebulab/solidus_paypal_commerce_platform#28]
> Yes - multiple purchase units implies multiple payments, but Solidus handles multiple payments already... by creating new payments. And one payment should only have one capture. The way it's build now makes it impossible AFAIK to have multiple purchase_units.
>
> However, now that we know more about the PayPal API, we could restructure the way we process the payments. In PayPal, you create an order, and that order can have multiple purchase units, which can have multiple captures. Purchase units can be used with partial orders, but since Solidus payments don't really care about partial orders (just the order total) I think we should stick with there being only one purchase_unit per order.
> 
> Currently we're structured as: Each payment has it's own PayPal order, which has one purchase unit and one capture
> 
> But we could structure it as: Each order has one Paypal order, which has one purchase unit, and each payment on the order has it's own capture.
> 
> However authorizing and capturing happens at the order level for PayPal, so while it conforms with our data a bit better, I'm not sure how much sense it makes. 🤔

_Originally posted by @seand7565 in https://github.com/nebulab/solidus_paypal_commerce_platform/pull/21_

**Comment by seand7565** [comment]
Seeing as how capturing and authorizing happen on the `order` level for PayPal, IMO the way we have this structured now makes the most sense.

**Comment by elia** [comment]
👍 makes sense
