### ISSUE TITLE
Allow checkout on product/cart page to complete the order

### ISSUE THREAD

**Issue by seand7565** [nebulab/solidus_paypal_commerce_platform#44]
As of #43 , the user is always brought to the order confirmation page upon returning from checking out on PayPal. In some cases this is fine, but in cases where the confirmation checkout step doesn't exist, we'll want the PayPal checkout process to be able to complete the order instead. 

Or maybe we should just add a bit to the README about it... Removing the confirmation step is a pretty big alteration to Solidus, so I don't think it's unreasonable if we didn't support it. Also, if they've customized the checkout heavily, it's likely whatever solution we put in place won't be sufficient. @elia what do you think?

**Comment by elia** [comment]
> Or maybe we should just add a bit to the README about it... Removing the confirmation step is a pretty big alteration to Solidus, so I don't think it's unreasonable if we didn't support it. Also, if they've customized the checkout heavily, it's likely whatever solution we put in place won't be sufficient. @elia what do you think?

Agree 💯 %, let's just mention that in the readme 👍
