### ISSUE TITLE
Digital goods should be set as not requiring shipment

### ISSUE THREAD

**Issue by seand7565** [nebulab/solidus_paypal_commerce_platform#46]
From the SOW:

```
If an order does not require any shipping information (Example: Digital Goods, Services), then
application_context>>shipping_preference in /v2/checkout/orders should be set to
NO_SHIPPING to suppress the shipping information on the PayPal Review page.
```

Perhaps we could implement a payment_method method that just returns true, expecting users to override the method if their store depends on digital goods?
```ruby
def shipment_required?
  true
end
```

**Comment by elia** [comment]
> NO_SHIPPING. Redact the shipping address from the PayPal site. Recommended for digital goods.
https://developer.paypal.com/docs/api/orders/v2/#definition-order_application_context

Since it's just recommended we could just avoid it if we still require the address in Solidus.
