### ISSUE TITLE
Explore subscribing to webhooks

### ISSUE THREAD

**Issue by seand7565** [nebulab/solidus_paypal_commerce_platform#70]
From Hai - 
`Are you subscribed to any webhooks? Since this is a 1st party integration, you wouldn’t be able to subscribe to any onboarding webhooks. However, if every shopping cart comes with a webhook listener built in then you can still subscribe to payment/orders webhooks. For a full list of webhooks see this link. Once you have subscribed to the webhooks that works for your use case, please let me know and we can test it.
`
Link: https://developer.paypal.com/docs/api-basics/notifications/webhooks/event-names/#paypal-commerce-platform

**Comment by elia** [comment]
Additionally, among the best practices this is listed:

> Following Webhooks are recommended to be subscribed to, to get real time notifications on Payments:
> o CHECKOUT.ORDER.PROCESSED
> o PAYMENT.CAPTURE.COMPLETED o PAYMENT.CAPTURE.DENIED
> o PAYMENT.CAPTURE.REFUNDED

**Comment by seand7565** [comment]
This was closed by #83 🎉
