### ISSUE TITLE
Explore enabling the payment method by default

### ISSUE THREAD

**Issue by seand7565** [nebulab/solidus_paypal_commerce_platform#71]
We've got the payment method disabled by default - because we want to ensure the users email is confirmed before proceeding. The current flow is:
`Create payment method -> Set "PayPal Email Confirmed" to true -> Set "Available to Users" to true`

Which is a bit unwieldy. I think enabling the payment method by default is fine, but then the "PayPal Email Confirmed" check is useless. 

From Hai - 

`In the admin panel, the admin/merchant has to click “Available to users” — will this be enabled by default? I believe it should be to make the setup/onboarding process smoother for merchants.`

**Comment by elia** [comment]
We could turn the check into an alert box of some kind that reminds the users to confirm the email address, optionally we can include a link (target=_blank) to where the confirmation is supposed to happen, or to a page that allows resending it, or to some PP documentation.
